# ITMGT 25.03 EE
# Assignment 3A

This is a data-cleaning assignment and is the first of two parts. The second part (3B) will be given Monday or Tuesday next week. This notebook is uploaded to our Github repository along with a csv of fake, dirty data called **recweekdata.csv**.


The output of this assignment is to convert recweekdata.csv into processable data for statistics. Submit the following files through GitHub:
1. A cleaned recweekdata.csv called cleanrecweekdata.csv **(5 points)**
2. This notebook, containing the code (properly commented) that you used to clean the data **(5 points)**
3. An html file of summary statistics from each column called **stats.html**. The requirements for the summary statistics are described below. **(10 points)**

This entire assignment (3A) is worth 20 points.

Upload your output files to your Github repositories. Make sure to send an email to **joben.ilagan@gmail.com** once you're done.

This assignment is due on **Tuesday, July 9, 2019** at 12:00NN.

In [56]:
## Code goes here

import csv
import re

recweekdata = list()

with open('recweekdata.csv') as csv_file:
    csv_reader = csv.reader(csv_file, delimiter =',')
    line_count = 0
    for row in csv_reader:
        if line_count==0:
            pass
        else:
            recweekdata.append({"first_name":row[0], "last_name":row[1], "birth_month":row[2], "birth_day":row[3],"birth_year":row[4],"course":row[5],"phone_number":row[6]})
        line_count += 1


In [57]:
#first name list

first_name = list() 
counter=0
for i in recweekdata:
    first_name.append(recweekdata[counter]["first_name"])
    counter+=1
    
#last name list 

last_name = list() 
counter=0
for i in recweekdata:
    last_name.append(recweekdata[counter]["last_name"])
    counter+=1
    
#birth day list

birth_day = list() 
counter=0
for i in recweekdata:
    birth_day.append(recweekdata[counter]["birth_day"])
    counter+=1

In [58]:
#cleaned birth months
#d_birth_month = dirty birth month
#c_birth_month = cleaned birth month

d_birth_month=list() 
counter=0
for i in recweekdata:
    d_birth_month.append(recweekdata[counter]['birth_month'])
    counter+=1

    unique_birth_month = set(d_birth_month)
unique_month_dict = {name:None for name in unique_birth_month}

for i in unique_month_dict:
    final_name = input(i+": "+"Enter name: ")
    unique_month_dict[i]=final_name

c_birth_month = [re.sub(r''.join(birth_month),r''.join(unique_month_dict[birth_month]),birth_month) for birth_month in d_birth_month]
c_birth_month


May: Enter name: May
Jan: Enter name: January
Jun: Enter name: June
7: Enter name: July
July: Enter name: July
Mar: Enter name: March
4: Enter name: April
5: Enter name: May
Feb: Enter name: February
Oct: Enter name: October
8: Enter name: August
April: Enter name: April
2: Enter name: February
September: Enter name: September
10: Enter name: October
February: Enter name: February
August: Enter name: August
11: Enter name: November
Sep: Enter name: September
December: Enter name: December
March: Enter name: March
Apr: Enter name: April
6: Enter name: June
June: Enter name: June
Dec: Enter name: December
3: Enter name: March
1: Enter name: January
9: Enter name: September
12: Enter name: December
Aug: Enter name: August
January: Enter name: January
November: Enter name: November
Jul: Enter name: July
Nov: Enter name: November


['November',
 'May',
 'May',
 'December',
 'September',
 'March',
 'November',
 'August',
 'July',
 'September',
 'December',
 'May',
 'January',
 'January',
 'June',
 'April',
 'January',
 'April',
 'December',
 'March',
 'July',
 'September',
 'April',
 'October',
 'May',
 'December',
 'March',
 'November',
 'October',
 'May',
 'April',
 'July',
 'December',
 'October',
 'July',
 'December',
 'February',
 'August',
 'May',
 'February',
 'November',
 'September',
 'January',
 'February',
 'January',
 'December',
 'August',
 'April',
 'October',
 'March',
 'August',
 'March',
 'December',
 'July',
 'May',
 'September',
 'May',
 'April',
 'April',
 'August',
 'September',
 'December',
 'February',
 'November',
 'March',
 'September',
 'December',
 'November',
 'November',
 'May',
 'August',
 'December',
 'June',
 'October',
 'September',
 'February',
 'May',
 'September',
 'December',
 'August',
 'February',
 'November',
 'June',
 'February',
 'January',
 'November',
 'August',
 'Januar

In [59]:
#cleaned birth year

d_birth_year=list() 
c_birth_year=list()
counter=0
for i in recweekdata:
    d_birth_year.append(recweekdata[counter]['birth_year'])
    counter+=1

for i in d_birth_year:
    if len(i)==4:
        c_birth_year.append(i)
    else:
        if i[0] == 0:
            c_birth_year.append('20'+i)
        else:
            c_birth_year.append('19'+i)
c_birth_year

['1998',
 '2001',
 '1997',
 '1997',
 '1997',
 '1999',
 '1998',
 '1999',
 '1997',
 '2001',
 '1998',
 '1997',
 '1999',
 '1999',
 '1998',
 '1999',
 '1997',
 '1997',
 '1997',
 '1997',
 '1999',
 '1999',
 '1997',
 '1997',
 '1997',
 '1999',
 '1997',
 '2000',
 '1999',
 '1999',
 '1999',
 '1999',
 '1999',
 '1999',
 '2001',
 '1998',
 '2000',
 '2001',
 '1997',
 '1998',
 '1999',
 '1998',
 '1999',
 '1998',
 '1997',
 '1998',
 '1999',
 '1999',
 '1997',
 '2001',
 '1998',
 '1999',
 '2000',
 '1998',
 '1998',
 '1998',
 '2001',
 '1997',
 '1998',
 '1999',
 '1998',
 '2000',
 '2000',
 '1997',
 '1997',
 '1997',
 '1997',
 '2001',
 '1998',
 '1998',
 '1999',
 '1999',
 '1998',
 '1997',
 '1998',
 '1997',
 '2000',
 '2000',
 '2000',
 '1999',
 '1997',
 '1997',
 '2000',
 '1999',
 '1999',
 '1998',
 '1998',
 '1997',
 '1998',
 '1999',
 '1997',
 '1997',
 '1998',
 '1997',
 '2001',
 '1999',
 '1997',
 '1998',
 '1998',
 '1999',
 '1997',
 '2001',
 '2000',
 '2001',
 '1999',
 '1997',
 '2001',
 '1999',
 '1998',
 '1999',
 '2001',
 

In [31]:
#cleaned courses

d_course=list() 
counter=0
for i in recweekdata:
    d_course.append(recweekdata[counter]['course'])
    counter+=1

    unique_course = set(d_course)
unique_course_dict = {name:None for name in unique_course}

for i in unique_course_dict:
    final_name = input(i+": "+"Enter name: ")
    unique_course_dict[i]=final_name

c_course = [re.sub(r''.join(course),r''.join(unique_course_dict[course]),course) for course in d_course]
c_course


BS MGT: Enter name: BS Management
ITE: Enter name: BS Information Technology Entrepreneurship 
BS LM: Enter name: BS Legal Management
BS CTM: Enter name: BS Communications Technology
Management Engineering: Enter name: BS Management Engineering
LM: Enter name: BS Legal Management
BS ITE: Enter name: BS Information Technology Entrepreneurship 
CTM: Enter name: BS Communications Technology
MGT: Enter name: BS Management
Communications Technology: Enter name: BS Communications Technology
BS ME: Enter name: BS Management Engineering
Management: Enter name: BS Management 
ME: Enter name: BS Management Engineering
Legal Management: Enter name: BS Legal Management
Information Technology Entrepreneurship: Enter name: BS Information Technology Entrepreneurship 


['BS Legal Management',
 'BS Management ',
 'BS Communications Technology',
 'BS Information Technology Entrepreneurship ',
 'BS Communications Technology',
 'BS Management ',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology',
 'BS Legal Management',
 'BS Management Engineering',
 'BS Communications Technology',
 'BS Management',
 'BS Information Technology Entrepreneurship ',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship ',
 'BS Management',
 'BS Information Technology Entrepreneurship ',
 'BS Management Engineering',
 'BS Legal Management',
 'BS Information Technology Entrepreneurship ',
 'BS Management',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Management Engineering',
 'BS Communications Technology',
 'BS Legal Management',
 'BS Legal Management',
 'BS Communications Technology',
 'BS Information Technology Entrepreneurship ',
 'BS Management ',
 'BS Information Technolo

In [30]:
#cleaned phone numbers

d_phone_number=list() 
c_phone_number=list()
counter=0
for i in recweekdata:
    d_phone_number.append(recweekdata[counter]['phone_number'])
    counter+=1
for i in d_phone_number:
    cleaned_phone_number = re.search(r'9.+.', i).group()
    c_phone_number.append("0"+cleaned_phone_number)



['0918 302 6210',
 '0927 212 6276',
 '0918 253 7017',
 '0918 714 4360',
 '0927 462 1674',
 '0918 629 5268',
 '0917 369 7388',
 '0917 240 6000',
 '0918 226 5748',
 '0918 342 1717',
 '0927 708 1308',
 '0927 747 5497',
 '0917 959 4490',
 '0927 543 4192',
 '0917 211 9497',
 '0918 185 5162',
 '0927 146 8146',
 '0927 516 4280',
 '0927 958 6909',
 '0917 514 9105',
 '0927 984 7499',
 '0927 699 3694',
 '0917 317 2478',
 '0917 159 3829',
 '0918 898 6972',
 '0917 796 4622',
 '0927 138 7580',
 '0917 195 9244',
 '0917 643 3996',
 '0917 758 3119',
 '0918 669 4265',
 '0917 750 8539',
 '0927 236 9504',
 '0917 438 4447',
 '0917 773 6035',
 '0918 455 4185',
 '0927 889 9252',
 '0927 874 8083',
 '0927 842 3053',
 '0927 923 1234',
 '0918 381 4956',
 '0918 602 9278',
 '0918 532 6748',
 '0917 654 1291',
 '0918 244 1683',
 '0917 818 1190',
 '0917 468 6425',
 '0918 635 1688',
 '0917 821 1896',
 '0927 924 9506',
 '0918 854 2626',
 '0918 438 9745',
 '0917 893 8235',
 '0918 216 5250',
 '0917 257 1057',
 '0927 949

In [73]:
cleaned_data=zip(first_name,last_name,c_birth_month,birth_day,c_birth_year,c_course,c_phone_number)
cleaned_data=list(cleaned_data)

In [77]:
#Writing csv file of cleaned data

import csv

row = ["first name","last name","birth month","birth day","birth year","course","phone number"]

with open('cleanrecweekdata.csv', 'a') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerow(row)
    for i in cleaned_data:
            writer.writerow(i)
csvFile.close()


# Required Summary Statistics
1. How many people were born in each month?
2. How many people were born on each day?
3. How many people were born in each year?
4. How many people come from each course?
5. How many people have numbers from Globe (0917 or 0927) and Smart (0918)? *Note: it's up to you how to format this output*

Answer these questions in an html file called stats.html. The format of the html is as follows (in template form, so you can use this as format string in your program, though feel free to modify with variable names if you find it easier to do so):


```
<html>
    <body>
         <h2>Summary Statistics</h2>
         <table>
             <tr><th>Stat</th><th>Value</th></tr>
             <tr><td>People born in each month</td><td>{}</td></tr>
             <tr><td>People born on each day</td><td>{}</td></tr>
             <tr><td>People born in each year</td><td>{}</td></tr>
             <tr><td>People coming from each course</td><td>{}</td></tr>
             <tr><td>People having numbers from Globe and Smart</td><td>{}</td></tr>
         </table>
    </body>
</html>
```

In [94]:
my_html = """
    <html>
    <body>
         <h2>Summary Statistics</h2>
         <table>
             <tr><th>Stat</th><th>Value</th></tr>
             <tr><td>People born in each month</td><td>{'November': 277,
 'May': 273,
 'December': 276,
 'September': 232,
 'March': 246,
 'August': 241,
 'July': 249,
 'January': 270,
 'June': 259,
 'April': 267,
 'October': 178,
 'February': 232}</td></tr>
             <tr><td>People born on each day</td><td>{'26': 116,
 '16': 115,
 '9': 98,
 '5': 100,
 '2': 106,
 '10': 111,
 '28': 104,
 '14': 102,
 '8': 111,
 '4': 110,
 '11': 105,
 '6': 99,
 '20': 91,
 '3': 90,
 '13': 119,
 '15': 121,
 '1': 112,
 '17': 116,
 '25': 116,
 '27': 102,
 '24': 108,
 '23': 116,
 '22': 103,
 '21': 123,
 '7': 88,
 '19': 113,
 '12': 98,
 '18': 107}</td></tr>
             <tr><td>People born in each year</td><td>{'1998': 746, '2001': 362, '1997': 756, '1999': 756, '2000': 380}</td></tr>
             <tr><td>People coming from each course</td><td>{'BS Legal Management': 585,
 'BS Management ': 214,
 'BS Communications Technology': 589,
 'BS Information Technology Entrepreneurship ': 590,
 'BS Management Engineering': 607,
 'BS Management': 415}</td></tr>
             <tr><td>People having numbers from Globe and Smart</td><td>{'Globe': 2045, 'Smart': 955}</td></tr>
         </table>
    </body>
    </html>
"""

with open('stats.html',"w+") as file:
    file.write(my_html)

In [84]:
#Month tally

month_tally={}

for month in c_birth_month:
    month_tally.setdefault(month,c_birth_month.count(month))
month_tally

{'November': 277,
 'May': 273,
 'December': 276,
 'September': 232,
 'March': 246,
 'August': 241,
 'July': 249,
 'January': 270,
 'June': 259,
 'April': 267,
 'October': 178,
 'February': 232}

In [85]:
#Day tally

day_tally={}

for day in birth_day:
    day_tally.setdefault(day,birth_day.count(day))
day_tally

{'26': 116,
 '16': 115,
 '9': 98,
 '5': 100,
 '2': 106,
 '10': 111,
 '28': 104,
 '14': 102,
 '8': 111,
 '4': 110,
 '11': 105,
 '6': 99,
 '20': 91,
 '3': 90,
 '13': 119,
 '15': 121,
 '1': 112,
 '17': 116,
 '25': 116,
 '27': 102,
 '24': 108,
 '23': 116,
 '22': 103,
 '21': 123,
 '7': 88,
 '19': 113,
 '12': 98,
 '18': 107}

In [86]:
#Year tally

year_tally={}

for year in c_birth_year:
    year_tally.setdefault(year,c_birth_year.count(year))
year_tally

{'1998': 746, '2001': 362, '1997': 756, '1999': 756, '2000': 380}

In [87]:
#Course tally

course_tally={}

for course in c_course:
    course_tally.setdefault(course,c_course.count(course))
course_tally

{'BS Legal Management': 585,
 'BS Management ': 214,
 'BS Communications Technology': 589,
 'BS Information Technology Entrepreneurship ': 590,
 'BS Management Engineering': 607,
 'BS Management': 415}

In [93]:
#Phone number tally

number_tally={"Globe":0,"Smart":0}
first_four_digits_list=[]
for i in c_phone_number:
    first_four_digits_list.append(i[0:4])

for number in first_four_digits_list:
    if number== "0917" or number=="0927":
        number_tally["Globe"]+=1
    elif number=="0918":
        number_tally["Smart"]+=1
        
number_tally

{'Globe': 2045, 'Smart': 955}